#!/bin/sh
# Generated by tooling/release/render-install.mjs; edit the shared template.
set -eu

# Do not execute a partial script when invoked through curl | sh.
main() {
  version=${INFOMENTOR_VERSION:-0.6.0}
  prefix=${INFOMENTOR_PREFIX:-${HOME:?Set HOME or INFOMENTOR_PREFIX}/.local}
  case "$version" in ''|*[!0-9A-Za-z.+-]*) echo 'Invalid INFOMENTOR_VERSION.' >&2; exit 1 ;; esac
  case "$prefix" in /*) ;; *) echo 'INFOMENTOR_PREFIX must be an absolute path.' >&2; exit 1 ;; esac
  network=''
  case "$*" in '') ;; --with-warp) network=warp ;; --without-warp) network=direct ;; *) echo 'Usage: install.sh [--with-warp|--without-warp]' >&2; exit 1 ;; esac
  for tool in curl tar mktemp uname; do
    command -v "$tool" >/dev/null 2>&1 || { printf 'Required command missing: %s\n' "$tool" >&2; exit 1; }
  done
  if command -v sha256sum >/dev/null 2>&1; then checksum_tool=sha256sum
  elif command -v shasum >/dev/null 2>&1; then checksum_tool='shasum -a 256'
  else echo 'Install sha256sum or shasum, then retry.' >&2; exit 1
  fi
  case "$(uname -s)" in Darwin) platform=darwin ;; Linux) platform=linux ;; *) echo 'Supported systems: macOS and Linux.' >&2; exit 1 ;; esac
  case "$(uname -m)" in arm64|aarch64) arch=arm64 ;; x86_64|amd64) arch=x64 ;; *) echo 'Supported CPUs: arm64 and x64.' >&2; exit 1 ;; esac
  [ -n "$network" ] || network=$(cat "$prefix/share/infomentor-mcp/network" 2>/dev/null || printf direct)
  case "$network" in direct|warp) ;; *) echo 'Invalid saved network setting.' >&2; exit 1 ;; esac
  if [ "$network" = warp ] && { [ "$platform" != linux ] || [ "$arch" != x64 ]; }; then echo 'Automatic WARP setup supports Debian 13 on x64.' >&2; exit 1; fi
  temporary=$(mktemp -d "${TMPDIR:-/tmp}/infomentor-install.XXXXXX")
  staging=
  command_tmp=
  trap 'rm -rf "$temporary"; if [ -n "$staging" ]; then rm -rf "$staging"; fi; if [ -n "$command_tmp" ]; then rm -rf "$command_tmp"; fi' 0
  trap 'exit 1' 1 2 15
  archive="infomentor-mcp-$version-$platform-$arch.tar.gz"
  release="https://github.com/olafurns7/family-mcp/releases/download/infomentor-mcp@$version"
  curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release/$archive" -o "$temporary/$archive"
  curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release/$archive.sha256" -o "$temporary/checksum"
  actual=$(cd "$temporary" && $checksum_tool "$archive")
  [ "$actual" = "$(cat "$temporary/checksum")" ] || { echo 'Release checksum verification failed; nothing was installed.' >&2; exit 1; }
  digest=${actual%% *}
  mkdir -p "$prefix/share/infomentor-mcp" "$prefix/bin"
  [ ! -d "$prefix/bin/infomentor-mcp" ] || { echo 'Install destination is a directory; nothing was replaced.' >&2; exit 1; }
  staging=$(mktemp -d "$prefix/share/infomentor-mcp/.install.XXXXXX")
  mkdir -p "$staging/bin"
  # Extract only named members to new regular files; never extract archive paths or links.
  tar -xOzf "$temporary/$archive" 'infomentor-mcp/bin/infomentor-mcp' > "$staging/bin/infomentor-mcp"
  chmod 755 "$staging/bin/infomentor-mcp"
  [ "$("$staging/bin/infomentor-mcp" --version </dev/null)" = "$version" ] || { echo 'Downloaded executable returned an unexpected version; previous installation kept.' >&2; exit 1; }
  for file in LICENSE README.md THIRD_PARTY_NOTICES.txt; do
    tar -xOzf "$temporary/$archive" "infomentor-mcp/$file" > "$staging/$file"
  done
  if [ "$platform" = 'linux' ]; then
    mkdir -p "$staging/libexec"
    tar -xOzf "$temporary/$archive" 'infomentor-mcp/libexec/warp.sh' > "$staging/libexec/warp.sh"
    chmod 644 "$staging/libexec/warp.sh"
  fi
  if [ "$platform" = 'linux' ]; then
    mkdir -p "$staging/bin"
    tar -xOzf "$temporary/$archive" 'infomentor-mcp/bin/infomentor-mcp-warp' > "$staging/bin/infomentor-mcp-warp"
    chmod 755 "$staging/bin/infomentor-mcp-warp"
  fi
  entrypoint=infomentor-mcp
  if [ "$network" = warp ]; then
    # Administrator code always comes from the freshly verified named archive member.
    cp "$staging/libexec/warp.sh" "$temporary/warp.sh"
    if [ "$(id -u)" = 0 ]; then sh "$temporary/warp.sh" install </dev/null
    else sudo sh "$temporary/warp.sh" install </dev/null
    fi
    entrypoint=infomentor-mcp-warp
  fi
  install_dir="$prefix/share/infomentor-mcp/$version-$digest"
  if [ -e "$install_dir" ] || [ -L "$install_dir" ]; then
    [ ! -L "$install_dir" ] && [ -d "$install_dir" ] && [ "$("$install_dir/bin/infomentor-mcp" --version </dev/null)" = "$version" ] || { echo 'Existing installation is invalid.' >&2; exit 1; }
    rm -rf "$staging"
  else
    mv "$staging" "$install_dir"
  fi
  staging=
  command_tmp=$(mktemp -d "$prefix/bin/.infomentor-mcp.XXXXXX")
  ln -s "$install_dir/bin/$entrypoint" "$command_tmp/command"
  mv -f "$command_tmp/command" "$prefix/bin/infomentor-mcp"
  printf '%s\n' "$network" > "$temporary/network"
  mv -f "$temporary/network" "$prefix/share/infomentor-mcp/network"
  printf 'Installed infomentor-mcp %s at %s/bin/infomentor-mcp\n' "$version" "$prefix"
  printf 'Use that absolute path in your MCP client. Setup: https://github.com/olafurns7/family-mcp/tree/infomentor-mcp@%s/packages/infomentor-mcp#readme\n' "$version"
  case ":${PATH:-}:" in *":$prefix/bin:"*) ;; *) printf 'For terminal use, add %s/bin to PATH.\n' "$prefix" ;; esac
}

main "$@"
