#!/bin/sh
# Generated by tooling/release/render-install.mjs; edit the shared template.
set -eu

# Do not execute a partial script when invoked through curl | sh.
main() {
  version=${ABLER_VERSION:-0.5.3}
  prefix=${ABLER_PREFIX:-${HOME:?Set HOME or ABLER_PREFIX}/.local}
  case "$version" in ''|*[!0-9A-Za-z.+-]*) echo 'Invalid ABLER_VERSION.' >&2; exit 1 ;; esac
  case "$prefix" in /*) ;; *) echo 'ABLER_PREFIX must be an absolute path.' >&2; exit 1 ;; esac
  stop_running=false
  case "$#" in
    0) ;;
    1) [ "$1" = --stop-running ] || { echo 'Usage: install.sh [--stop-running]' >&2; exit 1; }; stop_running=true ;;
    *) echo 'Usage: install.sh [--stop-running]' >&2; exit 1 ;;
  esac
  for tool in curl tar mktemp uname ps id readlink sleep tr; do
    command -v "$tool" >/dev/null 2>&1 || { printf 'Required command missing: %s\n' "$tool" >&2; exit 1; }
  done
  if command -v sha256sum >/dev/null 2>&1; then checksum_tool=sha256sum
  elif command -v shasum >/dev/null 2>&1; then checksum_tool='shasum -a 256'
  else echo 'Install sha256sum or shasum, then retry.' >&2; exit 1
  fi
  case "$(uname -s)" in Darwin) platform=darwin ;; Linux) platform=linux ;; *) echo 'Supported systems: macOS and Linux.' >&2; exit 1 ;; esac
  case "$(uname -m)" in arm64|aarch64) arch=arm64 ;; x86_64|amd64) arch=x64 ;; *) echo 'Supported CPUs: arm64 and x64.' >&2; exit 1 ;; esac
  package_dir="$prefix/share/abler-mcp"
  current_uid=$(id -u)
  macos_lsof_available=false
  if [ "$platform" = darwin ] && command -v lsof >/dev/null 2>&1; then macos_lsof_available=true; fi

  process_is_current_user() {
    [ "$(ps -p "$1" -o uid= 2>/dev/null | tr -d '[:space:]')" = "$current_uid" ]
  }

  is_old_install_dir() {
    candidate=$1
    case "$candidate" in "$package_dir/"*) ;; *) return 1 ;; esac
    [ "$candidate" != "$install_dir" ] || return 1
    candidate_name=${candidate#"$package_dir"/}
    case "$candidate_name" in ''|.*|*/*) return 1 ;; esac
    [ -d "$candidate" ]
  }

  command_matches_install() {
    case "$1" in
      "$2/bin/abler-mcp"|"$2/bin/abler-mcp "*|"$2/bin/abler-mcp-warp"|"$2/bin/abler-mcp-warp "*|\
      /bin/sh\ "$2/bin/abler-mcp"|/bin/sh\ "$2/bin/abler-mcp "*|\
      /bin/sh\ "$2/bin/abler-mcp-warp"|/bin/sh\ "$2/bin/abler-mcp-warp "*|\
      sh\ "$2/bin/abler-mcp"|sh\ "$2/bin/abler-mcp "*|\
      sh\ "$2/bin/abler-mcp-warp"|sh\ "$2/bin/abler-mcp-warp "*) return 0 ;;
    esac
    return 1
  }

  macos_executable_matches_install() {
    mapped_executables=$(lsof -a -p "$1" -d txt -Fn 2>/dev/null || true)
    case "
$mapped_executables
" in
      *"
n$2/bin/abler-mcp
"*|*"
n$2/bin/abler-mcp-warp
"*) return 0 ;;
    esac
    return 1
  }

  process_matches_install() {
    process_is_current_user "$1" || return 1
    if [ "$platform" = linux ]; then
      executable=$(readlink "/proc/$1/exe" 2>/dev/null || true)
      case "$executable" in "$2/bin/abler-mcp"|"$2/bin/abler-mcp-warp") return 0 ;; esac
    elif [ "$macos_lsof_available" = true ]; then
      macos_executable_matches_install "$1" "$2" && return 0
    fi
    command=$(ps -p "$1" -o command= 2>/dev/null || true)
    command_matches_install "$command" "$2"
  }

  record_old_process() {
    while IFS="$(printf '\t')" read -r recorded_pid recorded_dir; do
      [ "$recorded_pid" = "$1" ] && return 0
    done < "$old_processes"
    printf '%s\t%s\n' "$1" "$2" >> "$old_processes"
  }

  detect_linux_processes() {
    for process_link in /proc/[0-9]*/exe; do
      [ -e "$process_link" ] || continue
      process_pid=${process_link#/proc/}
      process_pid=${process_pid%/exe}
      executable=$(readlink "$process_link" 2>/dev/null || true)
      case "$executable" in
        "$package_dir/"*/bin/abler-mcp|"$package_dir/"*/bin/abler-mcp-warp)
          candidate=${executable%/bin/*}
          ;;
        *) continue ;;
      esac
      is_old_install_dir "$candidate" || continue
      process_matches_install "$process_pid" "$candidate" || continue
      record_old_process "$process_pid" "$candidate"
    done
  }

  detect_command_processes() {
    for candidate in "$previous_install_dir" "$package_dir"/*; do
      is_old_install_dir "$candidate" || continue
      ps -axo pid=,command= | while read -r process_pid command; do
        case "$process_pid" in ''|*[!0-9]*) continue ;; esac
        process_matches_install "$process_pid" "$candidate" || continue
        record_old_process "$process_pid" "$candidate"
      done
    done
  }

  detect_macos_symlink_processes() {
    [ "$platform" = darwin ] && [ "$macos_lsof_available" = false ] || return 0
    ps -axo pid=,command= | while read -r process_pid command; do
      case "$process_pid" in ''|*[!0-9]*) continue ;; esac
      process_is_current_user "$process_pid" || continue
      case "$command" in "$prefix/bin/abler-mcp"|"$prefix/bin/abler-mcp "*) ;; *) continue ;; esac
      record_old_process "$process_pid" ''
    done
  }

  detect_old_processes() {
    [ "$platform" != linux ] || detect_linux_processes
    detect_command_processes
    detect_macos_symlink_processes
  }

  temporary=$(mktemp -d "${TMPDIR:-/tmp}/abler-install.XXXXXX")
  staging=
  command_tmp=
  trap 'rm -rf "$temporary"; if [ -n "$staging" ]; then rm -rf "$staging"; fi; if [ -n "$command_tmp" ]; then rm -rf "$command_tmp"; fi' 0
  trap 'exit 1' 1 2 15
  archive="abler-mcp-$version-$platform-$arch.tar.gz"
  release="https://github.com/olafurns7/family-mcp/releases/download/abler-mcp@$version"
  curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release/$archive" -o "$temporary/$archive"
  curl --proto '=https' --proto-redir '=https' --tlsv1.2 -fsSL "$release/$archive.sha256" -o "$temporary/checksum"
  actual=$(cd "$temporary" && $checksum_tool "$archive")
  [ "$actual" = "$(cat "$temporary/checksum")" ] || { echo 'Release checksum verification failed; nothing was installed.' >&2; exit 1; }
  digest=${actual%% *}
  mkdir -p "$package_dir" "$prefix/bin"
  [ ! -d "$prefix/bin/abler-mcp" ] || { echo 'Install destination is a directory; nothing was replaced.' >&2; exit 1; }
  staging=$(mktemp -d "$package_dir/.install.XXXXXX")
  mkdir -p "$staging/bin"
  # Extract only named members to new regular files; never extract archive paths or links.
  tar -xOzf "$temporary/$archive" 'abler-mcp/bin/abler-mcp' > "$staging/bin/abler-mcp"
  chmod 755 "$staging/bin/abler-mcp"
  [ "$("$staging/bin/abler-mcp" --version </dev/null)" = "$version" ] || { echo 'Downloaded executable returned an unexpected version; previous installation kept.' >&2; exit 1; }
  for file in LICENSE README.md THIRD_PARTY_NOTICES.txt; do
    tar -xOzf "$temporary/$archive" "abler-mcp/$file" > "$staging/$file"
  done

  entrypoint=abler-mcp

  install_dir="$prefix/share/abler-mcp/$version-$digest"
  if [ -e "$install_dir" ] || [ -L "$install_dir" ]; then
    [ ! -L "$install_dir" ] && [ -d "$install_dir" ] && [ "$("$install_dir/bin/abler-mcp" --version </dev/null)" = "$version" ] || { echo 'Existing installation is invalid.' >&2; exit 1; }
    rm -rf "$staging"
  else
    mv "$staging" "$install_dir"
  fi
  staging=
  previous_install_dir=
  if [ -L "$prefix/bin/abler-mcp" ]; then
    previous_target=$(readlink "$prefix/bin/abler-mcp" 2>/dev/null || true)
    case "$previous_target" in
      "$package_dir/"*/bin/abler-mcp|"$package_dir/"*/bin/abler-mcp-warp)
        previous_install_dir=${previous_target%/bin/*}
        ;;
    esac
  fi
  command_tmp=$(mktemp -d "$prefix/bin/.abler-mcp.XXXXXX")
  ln -s "$install_dir/bin/$entrypoint" "$command_tmp/command"
  mv -f "$command_tmp/command" "$prefix/bin/abler-mcp"

  old_processes="$temporary/old-processes"
  : > "$old_processes"
  detect_old_processes
  if [ -s "$old_processes" ]; then
    if [ "$stop_running" = true ]; then
      while IFS="$(printf '\t')" read -r process_pid candidate; do
        [ -n "$candidate" ] || continue
        process_matches_install "$process_pid" "$candidate" || continue
        kill -TERM "$process_pid" 2>/dev/null || true
      done < "$old_processes"
      waited=0
      while :; do
      running=false
      while IFS="$(printf '\t')" read -r process_pid candidate; do
          if [ -n "$candidate" ] && process_matches_install "$process_pid" "$candidate"; then running=true; fi
      done < "$old_processes"
        if [ "$running" = false ]; then break; fi
        if [ "$waited" -ge 10 ]; then break; fi
        sleep 1
        waited=$((waited + 1))
      done
      remaining=false
      while IFS="$(printf '\t')" read -r process_pid candidate; do
        if [ -z "$candidate" ]; then
          printf 'Possibly old abler-mcp process still running: PID %s (version unknown)\n' "$process_pid"
          remaining=true
        elif process_matches_install "$process_pid" "$candidate"; then
          printf 'Old abler-mcp process still running after SIGTERM: PID %s (%s)\n' "$process_pid" "$candidate"
          remaining=true
        else
          printf 'Stopped old abler-mcp process: PID %s (%s)\n' "$process_pid" "$candidate"
        fi
      done < "$old_processes"
      if [ "$remaining" = true ]; then
        printf 'Install succeeded, but old abler-mcp processes remained after SIGTERM. Restart your MCP host after stopping them.\n' >&2
        return 1
      fi
    else
      while IFS="$(printf '\t')" read -r process_pid candidate; do
        if [ -n "$candidate" ]; then
          printf 'Old abler-mcp process still running: PID %s (%s)\n' "$process_pid" "$candidate"
        else
          printf 'Possibly old abler-mcp process still running: PID %s (version unknown)\n' "$process_pid"
        fi
      done < "$old_processes"
      printf 'Restart your MCP host (Claude Desktop / Claude Code / Codex / the bot) so it starts the new version, or rerun this installer with --stop-running to send those processes SIGTERM.\n'
    fi
  fi
  printf 'Installed abler-mcp %s at %s/bin/abler-mcp\n' "$version" "$prefix"
  printf 'Use that absolute path in your MCP client. Setup: https://github.com/olafurns7/family-mcp/tree/abler-mcp@%s/packages/abler-mcp#readme\n' "$version"
  case ":${PATH:-}:" in *":$prefix/bin:"*) ;; *) printf 'For terminal use, add %s/bin to PATH.\n' "$prefix" ;; esac
}

main "$@"
